export const dummySkills: SkillRecord[] = [
  {
    id: "skill_001",
    title: "Write Code",
    slug: "write-code",
    description: "Generates high-quality code based on user requirements and best practices.",
    category: "development",
    tags: ["code-generation", "ai", "programming"],
    installCommand: "npm install @skild/write-code",
    createdAt: "2024-01-15T10:00:00Z",
    authorClerkId: "user_demo_001",
    authorEmail: "demo@example.com",
  },
  {
    id: "skill_002",
    title: "Debug Errors",
    slug: "debug-errors",
    description: "Helps diagnose and fix software bugs with detailed error analysis.",
    category: "development",
    tags: ["debugging", "troubleshooting", "error-fixing"],
    installCommand: "npm install @skild/debug-errors",
    createdAt: "2024-01-16T10:00:00Z",
    authorClerkId: "user_demo_002",
    authorEmail: "demo2@example.com",
  },
  {
    id: "skill_003",
    title: "Review Code",
    slug: "review-code",
    description: "Performs automated code reviews for quality, security, and best practices.",
    category: "review",
    tags: ["code-review", "quality", "security"],
    installCommand: "npm install @skild/review-code",
    createdAt: "2024-01-17T10:00:00Z",
    authorClerkId: "user_demo_003",
    authorEmail: "demo3@example.com",
  },
  {
    id: "skill_004",
    title: "Refactor Code",
    slug: "refactor-code",
    description: "Improves code structure and readability while maintaining functionality.",
    category: "development",
    tags: ["refactoring", "optimization", "clean-code"],
    installCommand: "npm install @skild/refactor-code",
    createdAt: "2024-01-18T10:00:00Z",
    authorClerkId: "user_demo_004",
    authorEmail: "demo4@example.com",
  },
  {
    id: "skill_005",
    title: "Write Tests",
    slug: "write-tests",
    description: "Generates comprehensive unit and integration tests for your code.",
    category: "testing",
    tags: ["testing", "unit-tests", "integration-tests"],
    installCommand: "npm install @skild/write-tests",
    createdAt: "2024-01-19T10:00:00Z",
    authorClerkId: "user_demo_005",
    authorEmail: "demo5@example.com",
  },
];